=============================
The ``0-add_integer`` module
=============================

Importing the ``add_integer`` function from the module:
======================================================
	>>> add_integer = __import__("0-add_integer").add_integer


Tests
================
*Test for regular addition:
	 >>> add_integer(1, 3)
	 4

*Test for positive with negative:
	 >>> add_integer(2, -1)
	 1

*Test for negative with positive:
	 >>> add_integer(-5, 2)
	 -3

*Test for float with int:
	 >>> add_integer(2.1, 5)
	 7

*Test for int with float:
	 >>> add_integer(5, 6.0)
	 11

*Test for both float:
	 >>> add_integer(1.9, 1.1)
	 2

*Test for super long int:
	 >>> add_integer(999999999999999999999999999999, 1)
	 1000000000000000000000000000000

*Test for more than 2 args:
	 >>> add_integer(0, 2, 4)
     Traceback (most recent call last):
     ...
     TypeError: add_integer() takes 2 arguments but 3 were given

*Test for passed NaN:
	 >>> add_integer(1, float('nan'))
	 Traceback (most recent call last):
	 ...
	 ValueError: cannot convert float NaN to integer

*Test for passed float infinity inf:
	 >>> add_integer(1, float('inf'))
	 Traceback (most recent call last):
	 ...
	 OverflowError: cannot convert float infinity to integer

*Test for non-number with number:
	 >>> add_integer([1], 2)
	 Traceback (most recent call last):
	 ...
	 TypeError: a must be an integer

*Test for number with non-number:
	 >>> add_integer(6, "1")
	 Traceback (most recent call last):
	 ...
	 TypeError: b must be an integer

*Test for non-number with non-number:
	 >>> add_integer((1,), {"key": "value"})
         Traceback (most recent call last):
         ...
         TypeError: a must be an integer

*Test for bool with number:
	 >>> add_integer(True, 3)
	 Traceback (most recent call last):
         ...
         TypeError: a must be an integer

*Test for number with bool:
	 >>> add_integer(2, False)
         Traceback (most recent call last):
         ...
         TypeError: b must be an integer

*Test for no args:
	 >>> add_integer()
	 Traceback (most recent call last):
	 ...
	 TypeError: add_integer() missing 2 required positional arguments: 'a' and 'b'

*Test for one arg:
	 >>> add_integer(1)
	 Traceback (most recent call last):
         ...
	 TypeError: add_integer() missing 1 required positional argument: 'b'

*Test for more than 2 args:
	 >>> add_integer(1, 2, 3)
         Traceback (most recent call last):
         ...
         TypeError: add_integer() takes 2 positional arguments but 3 were given